### ISSUE TITLE
在录制脚本后，再次执行该脚本时，提示“Error: /sdcard/Test.jar does not exist”

### ISSUE THREAD

**Issue by ZMiko** [chorushe/princekin#3]

**Comment by ZMiko** [comment]
D:\princekinWorkspace\yy\uiautomatorjava\jj\uu.java:3: 错误: 程序包com.android.uiautomator.core不存在

import com.android.uiautomator.core.UiDevice;

**Comment by chorushe** [comment]
写好的脚步需要编译、打包成功后才能运行；
出现“程序包com.android.uiautomator.core不存在”问题应该是android的环境没有搭建好，要把环境变量配置好，另外jdk仅支持1.7版本。

**Comment by ZMiko** [comment]
如果自己手动编写脚本的话，是否可以用python语言进行编写？有什么规范吗？如何执行

**Comment by chorushe** [comment]
我们已经封装了一部分命令，自己编写脚本时，可在新建脚本库之后，在文件列表里的command文件夹里看见具体命令的使用方法，暂时不支持其他语言编写。
