### ISSUE TITLE
Error: UI test projects can only target API 16 and above

### ISSUE THREAD

**Issue by ZMiko** [chorushe/princekin#4]
打包过程中，提示报错，Error: UI test projects can only target API 16 and above

这个应在哪里修改配置

**Comment by chorushe** [comment]
sdk的platform是不是有较低的版本，如果有，删除掉。

**Comment by ZMiko** [comment]
删除之后，再打包，报另外的错误，这个是什么原因道正的呢
打包中...
Updated file D:\princekinWorkspace\uu\uiautomatorjava\io\build.xml

Buildfile: D:\princekinWorkspace\uu\uiautomatorjava\io\build.xml



-check-env:

 [checkenv] Android SDK Tools Revision 25.2.5

 [checkenv] Installed at D:\Test\Appium\adt-bundle-windows-x86_64_20140101\sdk



-build-setup:

[getbuildtools] Using latest Build Tools: 23.0.3

     [echo] Resolving Build Target for io...

[getuitarget] Project Target:   Android 4.1.2

[getuitarget] API level:        16

     [echo] ----------

     [echo] Creating output directories if needed...



-pre-compile:



compile:



-post-compile:



-dex:

      [dex] input: D:\princekinWorkspace\uu\uiautomatorjava\io\bin\classes

      [dex] Converting compiled files and external libraries into D:\princekinWorkspace\uu\uiautomatorjava\io\bin\classes.dex...

       [dx] 

       [dx] UNEXPECTED TOP-LEVEL EXCEPTION:

       [dx] java.lang.RuntimeException: Exception parsing classes

       [dx] 	at com.android.dx.command.dexer.Main.processClass(Main.java:752)

       [dx] 	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718)

       [dx] 	at com.android.dx.command.dexer.Main.access$1200(Main.java:85)

       [dx] 	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1645)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:170)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)

       [dx] 	at com.android.dx.command.dexer.Main.processOne(Main.java:672)

       [dx] 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)

       [dx] 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)

       [dx] 	at com.android.dx.command.dexer.Main.run(Main.java:277)

       [dx] 	at com.android.dx.command.dexer.Main.main(Main.java:245)

       [dx] 	at com.android.dx.command.Main.main(Main.java:106)

       [dx] Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)

       [dx] 	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)

       [dx] 	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)

       [dx] 	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)

       [dx] 	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)

       [dx] 	at com.android.dx.command.dexer.Main.parseClass(Main.java:764)

       [dx] 	at com.android.dx.command.dexer.Main.access$1500(Main.java:85)

       [dx] 	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)

       [dx] 	at com.android.dx.command.dexer.Main.processClass(Main.java:749)

       [dx] 	... 19 more

       [dx] 

       [dx] UNEXPECTED TOP-LEVEL EXCEPTION:

       [dx] java.lang.RuntimeException: Exception parsing classes

       [dx] 	at com.android.dx.command.dexer.Main.processClass(Main.java:752)

       [dx] 	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718)

       [dx] 	at com.android.dx.command.dexer.Main.access$1200(Main.java:85)

       [dx] 	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1645)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:170)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)

       [dx] 	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)

       [dx] 	at com.android.dx.command.dexer.Main.processOne(Main.java:672)

       [dx] 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)

       [dx] 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)

       [dx] 	at com.android.dx.command.dexer.Main.run(Main.java:277)

       [dx] 	at com.android.dx.command.dexer.Main.main(Main.java:245)

       [dx] 	at com.android.dx.command.Main.main(Main.java:106)

       [dx] Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)

       [dx] 	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)

       [dx] 	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)

       [dx] 	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)

       [dx] 	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)

       [dx] 	at com.android.dx.command.dexer.Main.parseClass(Main.java:764)

       [dx] 	at com.android.dx.command.dexer.Main.access$1500(Main.java:85)

       [dx] 	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)

       [dx] 	at com.android.dx.command.dexer.Main.processClass(Main.java:749)

       [dx] 	... 19 more

       [dx] 2 errors; aborting



BUILD FAILED

D:\Test\Appium\adt-bundle-windows-x86_64_20140101\sdk\tools\ant\uibuild.xml:198: null returned: 1



Total time: 2 seconds

打包结束
